{% set name = "amazon-sagemaker-jupyter-scheduler" %}
{% set version = "3.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amazon_sagemaker_jupyter_scheduler-{{ version }}.tar.gz
  sha256: 43704a9565af806e86da272c36caee294e8659023ab78ca95f91103d50dd6cfc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - jupyter_packaging >=0.12.0,<0.13.dev0
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.7
    - aiobotocore >=2.9,<3
    - jupyter-scheduler >=2.7.*,<3
    - jupyter_server
    - jupyterlab ==4.*
    - sagemaker-jupyterlab-extension-common >=0.2.1,<1
    - aws-embedded-metrics
    - async-timeout
    - async-lru
    - pydantic
    - pytz
    - botocore
    - tornado

test:
  imports:
    - amazon_sagemaker_jupyter_scheduler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: Amazon SageMaker Jupyter Scheduler based on the https://pypi.org/project/jupyter-scheduler/
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - aws-jasakshi
    - aakashmandavilli96
    - pilgd-aws
    - meghanajs99
    - oztoprakmustafa
    - zuoyuanh
    - mufaddal-rohawala
    - benieric
